### ISSUE TITLE
Перевод слова Bundle

### ISSUE THREAD

**Issue by cursedcoder** [avalanche123/symfony-docs-ru#55]
Добрый день.

Заметил по документации, что слово `bundle` везде переводится как `пакет`.
Совсем не согласен с таким наименованием. Зачем переводить технические термины?

В [итальянской](http://symfony.com/it/doc/current/book/page_creation.html) документации всегда используется `bundle`.

В общем, я за то, чтобы добавить `bundle` —> `бандл` в глоссарий.

**Comment by inoryy** [comment]
разве Bundle не попадает под "служебные слова"? зачем его вообще как-то переводить?

**Comment by cursedcoder** [comment]
@Inori это нужно для упрощения склонения: бандл, бандла, бандле.

P.S. о, ещё 1 русскоговорящий человек в Knp =) не знал

**Comment by inoryy** [comment]
Я имею ввиду что есть определенный список слов а ля "Response", "Controller", которые не переводятся вообще, разве Bundle в него не включен?

**Comment by cursedcoder** [comment]
Это называется глоссарий, о чём я упоминал выше.

Я так понял, что в данном репозиторие придерживаются [этого](http://trac.symfony-project.org/wiki/РусскийГлоссарийSymfony) + несколько случаев в readme.

И да, такие термины не переводятся, это как traits в php 5.4.

**Comment by everzet** [comment]
Я вообще не вижу смысла в переводе технической документации. Но это я...

**Comment by everzet** [comment]
@cursedcoder 
`feed` - лента
`flash` - мгновенное сообщение
`helper` - помощник

Более чем сомнительно.

**Comment by inoryy** [comment]
Глоссарий - это другое, я про пункт 2 под "Не переводятся", выделенный жирным шрифтом в readme.md этого репа.

В общем лично мне "Bundle" был бы гораздо понятнее чем "банлд" и уж тем более "бандла", "бандле" - это вообще ночной кошмар для недофилолога во мне.

**Comment by cursedcoder** [comment]
@everzet поддерживаю, но в этом есть свои плюсы, например расширить аудиторию в странах СНГ(это конкретно русской документации).

**Comment by cursedcoder** [comment]
@Inori "Не переводятся" это лишь теги restructuredText'a

https://raw.github.com/avalanche123/symfony-docs-ru/26ec65622e109340d168de47abb05b70f18f2008/glossary.rst

``` jinja
   Пакет
        *Пакет* (Bundle), это директория, содержащая набор файлов
        (PHP-файлы, стили, яваскрипты, изображения), который *реализует*
        единичную фичу (блог, форум и т.д.). В Symfony2, *как правило*,
        всё распложено в пакетах (см. :ref:`page-creation-bundles`).
```

Так-же весьма сомнительно смотрятся: `Брандмауэр` `Действие` `Ресурс`, а особенно `Контейнер служб` и `Служба`

ping @avalanche123 @frost-nzcr4 @dbykadorov @stfalcon

**Comment by torchello** [comment]
"В Symfony2, _как правило_, всё распложено в пакетах" -- звучит очень странно :о Для меня английские слова выглядят привычней (или их кириллические аналоги для упрощения склонения).

**Comment by pilot** [comment]
Вообще это все как из фильма брилиантовая рука "неперводимая игра слов" - эти обозначения переводить не стоит, так как приводит к путанице, те мы говорим о:
- bundle
- service contaner

но при это вполне допустимо исопльзовать руссицизм данного слова в звучании как оно есть:
- бандл
- сервис контейнер

это нормальная практика по принципу как для имен, названий объектов, городов и тд
